version: "3.8"

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres # ← CAMBIATO per allinearsi al .env
      POSTGRES_PASSWORD: 1234 # ← CAMBIATO per allinearsi al .env
      POSTGRES_DB: merendels_db
    volumes:
      - ./db/backup.sql:/docker-entrypoint-initdb.d/01-backup.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # ← CORRETTO
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./merendels-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database # ← OVERRIDE per Docker (sovrascrive .env)
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: "1234"
      DB_NAME: merendels_db
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./merendels-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
